# MihuuTheme - alacritty color config
# MihaiStreames

[colors.primary]
background = "#0F122D"
foreground = "#c3c3ca"

[colors.cursor]
text = "#0F122D"
cursor = "#c3c3ca"

[colors.vi_mode_cursor]
text = "#0F122D"
cursor = "#c3c3ca"

[colors.search.matches]
foreground = "#0F122D"
background = "#c3c3ca"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#616277"
background = "#94959e"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#0F122D"
red = "#2d324e"
green = "#393755"
yellow = "#6f4a57"
blue = "#492373"
magenta = "#392f84"
cyan = "#3f3b71"
white = "#94959e"

[colors.bright]
black = "#616277"
red = "#3C4368"
green = "#4D4A72"
yellow = "#956375"
blue = "#622F9A"
magenta = "#4D3FB1"
cyan = "#554F97"
white = "#c3c3ca"

[colors.dim]
black = "#c3c3ca"
red = "#3C4368"
green = "#4D3FB1"
yellow = "#956375"
blue = "#622F9A"
magenta = "#4D4A72"
cyan = "#554F97"
white = "#616277"

[font]
size = 12

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
decorations = "none"
# opacity = 0.95

[window.dimensions]
columns = 100
lines = 24

[window.padding]
x = 20
y = 20
