[config]

[templates.kitty]
input_path = "templates/kitty-theme.conf"
output_path = "~/.config/kitty/theme.conf"
mode = "Dark"

[templates.hyprland]
input_path = "templates/hyprland-colors.conf"
output_path = "~/.config/hypr/conf/colors.conf"
mode = "Dark"

[templates.rofi]
input_path = "templates/rofi-colors.rasi"
output_path = "~/.config/rofi/shared/colors.rasi"
mode = "Dark"

[templates.waybar]
input_path = "templates/waybar-colors.css"
output_path = "~/.config/waybar/colors.css"
mode = "Dark"

[templates.fish]
input_path = "templates/fish-colors.fish"
output_path = "~/.config/fish/conf.d/02-colors.fish"
mode = "Dark"

[templates.dunst]
input_path = "templates/dunst-colors.conf"
output_path = "~/.config/dunst/dunstrc.d/colors.conf"
mode = "Dark"

[templates.wlogout]
input_path = "templates/wlogout-colors.css"
output_path = "~/.config/wlogout/colors.css"
mode = "Dark"

[templates.spicetify]
input_path = "templates/spicetify-color.ini"
output_path = "~/.config/spicetify/Themes/mochaccino/color.ini"
mode = "Dark"

[templates.sublime]
input_path = "templates/sublime-color-scheme.json"
output_path = "~/.config/sublime-text/Packages/User/Mochaccino.sublime-color-scheme"
mode = "Dark"

[templates.hyprlock]
input_path = "templates/hyprlock-colors.conf"
output_path = "~/.config/hypr/conf/hyprlock-colors.conf"
mode = "Dark"

[templates.grub-theme]
input_path = "templates/grub-theme.txt"
output_path = "themes/mochaccino/grub-theme.txt"
mode = "Dark"

[templates.sddm-theme]
input_path = "templates/sddm-theme.conf"
output_path = "themes/mochaccino/sddm-theme.conf"
mode = "Dark"

[templates.logo]
input_path = "templates/assets/ThemeLogo.svg"
output_path = "themes/mochaccino/ThemeLogo.svg"
mode = "Dark"

[templates.grub-background]
input_path = "templates/assets/grub-background.svg"
output_path = "themes/mochaccino/grub-background.svg"
mode = "Dark"

[templates.colors-cfg]
input_path = "templates/assets/colors.cfg"
output_path = "themes/mochaccino/colors.cfg"
mode = "Dark"
